### ISSUE TITLE
If you don't set the project Platform Target to x64 it will fail to load the sdk_wrapper_dotnet.dll

### ISSUE THREAD

**Issue by CJHarmath** [Azure-Samples/MipSDK-File-Dotnet-Quickstart#5]
With Any CPU it fails to load the native dll
```
***** Error!
oadLibrary failed for: [sdk_wrapper_dotnet.dll]
  at MipSdkDotNetQuickstart.Action..ctor(ApplicationInfo appInfo) in C:\dev\git\MipSdk-Dotnet-File-Quickstart\mip-sdk-dotnet-quickstart\Action.cs:line 92
  at MipSdkDotNetQuickstart.Program.Main(String[] args) in C:\dev\git\MipSdk-Dotnet-File-Quickstart\mip-sdk-dotnet-quikstart\Program.cs:line 61
```

Solution: Set platform to x64

**Comment by csharmath** [comment]
https://github.com/Azure-Samples/MipSdk-Dotnet-File-Quickstart/blob/master/mip-sdk-dotnet-quickstart/MipSdkDotNetQuickstart.csproj#L34
should be 

```
<PlatformTarget>x64</PlatformTarget>
```

Otherwise you can even run the sample.

**Comment by jojoblaze** [comment]
Apart of target to x64, I noticed that you need to run IIS in 64 bit mode.

Go to Tools -> Options -> Projects and Solutions -> Web Projects -> Use the 64 bit version of IIS Express…

**Comment by csharmath** [comment]
@jojoblaze Careful if you run this in a web app.
Remove all the .Result calls and do proper async await only methods.
I think there is only one method somewhere which is sync, so with that switch to do the recommended getawaiter getresult and probably configure await false.
So you don't get the aggregate exception and won't need synchronized context.
Also swap the throw ex to just throw to avoid ruining the stacktrace or just remove.

Some catches are also swallowing exceptions, so you need to fix those as well.

**Comment by kanishkaBagga** [comment]
It looks like you're encountering issues with building the MIP SDK File Dotnet Quickstart project in Visual Studio 2015 after downloading the necessary NuGet packages.


One potential issue could be related to the project Platform Target settings. If you don't set the project Platform Target to x64, it might fail to load certain DLLs, such as `sdk_wrapper_dotnet.dll` [1](https://outlook.office365.com/owa/?ItemID=AAMkADg4YzllMDBiLTlkMGItNDM5ZC1hNzliLWEyM2M4YmNmZGE5NABGAAAAAAB1y0RbhsUfQZ4O8VgqU3JiBwD5ID%2fxZZvdQqo2DTfBiP9ZAAAAAAEMAAD5ID%2fxZZvdQqo2DTfBiP9ZAAQEFmonAAA%3d&exvsurl=1&viewmodel=ReadMessageItem). Ensuring that your project is configured to target the correct platform might resolve this issue.


NuGet Package Restore -  Sometimes, broken package references after restoring NuGet packages can cause build failures. Try deleting the packages folder or the `obj/project.assets.json` file and running restore again.

Clearing Cache - Use the command `nuget locals all -clear` or `dotnet nuget locals all --clear` from the command line to clear the global packages and cache

Visual Studio Version - Consider upgrading to a newer version of Visual Studio if you are using newer package formats. Visual Studio 2015 does not support the new `.csproj` format, so migrating to Visual Studio 2017 or Visual Studio Code might be necessary (https://learn.microsoft.com/en-us/samples/azure-samples/mipsdk-dotnet-file-quickstart/mipsdk-file-dotnet-quickstart/).
